version: '3.8'

services:
  db:
    image: mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1000M
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 159487
      MYSQL_ROOT_DATABASE: comunique
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "3307:3306"
    volumes:
      - comunique:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  Java:
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1000M
    build:
      context: ..
      dockerfile: .devContainer/Dockerfile
      args:
        INSTALL_MAVEN: "true"
    image: "java-image"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ..:/app

    ports:
      - "8080:8080"

volumes:
  comunique:
