version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 159487
      MYSQL_ROOT_DATABASE: comunique
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./comunique.sql:/docker-entrypoint-initdb.d/init.sql

  Java:
    tty: true
    build:
      context: ..
      dockerfile: .devContainer/Dockerfile
      args:
        INSTALL_MAVEN: "true"
    image: "java-image"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ..:/app

    ports:
      - "8080:8080"

volumes:
  data:
